### ISSUE TITLE
[PR 前征询意见] 采用诸如 `nginx-ultimate-bad-bot-blocker` 之类的项目替代现有的反击 bot 配置

### ISSUE THREAD

**Issue by IceCodeNew** [FastGitORG/nginx-conf#10]
如题，现在的反黑 bot 配置是这样的：
```
    # Block search engine
    # if ($http_user_agent ~* "qihoobot|Baiduspider|Bingbot|Googlebot|Googlebot-Mobile|Googlebot-Image|Mediapartners-Google|Adsbot-Google|Feedfetcher-Google|Yahoo! Slurp|Yahoo! Slurp China|YoudaoBot|Sosospider|Sogou spider|Sogou web spider|MSNBot|ia_archiver|Tomato Bot")
    # {
    #     return 403;
    # }

    # Anti Agent Bot DDoS
    # If behind CDN, use folloing commented code
    # if ($http_x_forwarded_for != $remote_addr) {
    #     return 503;
    # }
    if ($proxy_add_x_forwarded_for != $remote_addr) {
        return 503;
    }
```

——我很欣赏这种土方法，真的（抹眼泪

之所以先发 Issue 来征询意见是因为我使用 `nginx-ultimate-bad-bot-blocker` 的经验也不是很长，本着负责任的态度，问问看其他人对这个或其他类似项目是怎么看的
我个人网站是无所谓怎么误伤国内访客/爬虫的，但对贵项目来说这个项目却不一定适合，有意向做些考察的话，请参考：https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker

**Comment by KevinZonda** [comment]
I have used robot.txt to anti robots.

**Comment by IceCodeNew** [comment]
> I have used robot.txt to anti robots.

我明白，不过这里说的是 bad bots，人家不遵守游戏规则的（

**Comment by KevinZonda** [comment]
> > I have used robot.txt to anti robots.
> 
> 我明白，不过这里说的是 bad bots，人家不遵守游戏规则的（

As open-source configs, I don't think we should consider so much.

**Comment by IceCodeNew** [comment]
> As open-source configs, I don't think we should consider so much.

你曰的有理，那我就不折腾了（幸好提前先问了一下

**Comment by KevinZonda** [comment]
@IceCodeNew XD
