### ISSUE TITLE
希望能对CORS跨域进行支持

### ISSUE THREAD

**Issue by juqkai** [FastGitORG/nginx-conf#25]
现在有个软件通过ajax下载插件，是通过github的/releases/download/来安装的。
由于fastgit的header中没有跨域的相关配置，所以无法在应用中下载到数据。
这里不管是直接使用`https://download.fastgit.org/xxx/xxx/releases/download/xxx/xxx.json`
还是`https://hub.fastgit.org/xxx/xxx/releases/download/xxx/xxx.json`
都无法在跨域的情况下访问。

建议添加类似的信息在header里面：

```
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
    add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';

```

**Comment by KevinZonda** [comment]
Hi, thank you for your interest in FastGit UK.  Currently, I have no idea to add such thing into the main conf. We have suffered plenty of spam, which means we have to be cautious during adding any function which might worse current situations. Apologise for the inconvenience caused again.

Many thanks,
KevinZonda
