### ISSUE TITLE
我注意到 `raw.fastgit.org` 没有压缩，而 Github Raw 自身却都压缩了，这是正常的么？

### ISSUE THREAD

**Issue by XIU2** [FastGitORG/nginx-conf#27]
我今天意外发现，同一个 Github 文件，
如果使用 ` raw.fastgit.org `，那么会是原始尺寸，检查头部没有发现压缩相关标识，即没有经过压缩。
如果通过 ` raw.githubusercontent.com ` 访问，那么会默认 Gzip 压缩，文件会小很多。

我也去看了一下其他的 Github Raw 加速服务，全部都进行了 Gzip 压缩以此来**减少服务器流量、宽带**，因此比较奇怪为什么 FastGit 没有这么做，是有什么特殊原因吗？或者这是一个错误？。。。

毕竟适当的压缩等级对服务器压力并不大，但却可以大幅降低服务器流量、宽带。

**Comment by XIU2** [comment]
我看了下 `raw.fastgit.org.conf` 文件，是这句代码导致的。

这句代码的意思是，反向代理时**告诉源服务器不要压缩**，而一般情况下无需添加这句代码，因为只有当你想要修改网页内容时（比如使用 `sub_filter` 来替换内容），才必须加上这个（否则会因为压缩而乱码）。

https://github.com/FastGitORG/nginx-conf/blob/a436ac717ae88c6916084d0542348efd6b2397a9/raw.fastgit.org.conf#L55

去掉这段代码后，应该就会得到压缩后的文件了（由 Github 服务器压缩），即和 `raw.githubusercontent.com` 完全一样。

**Comment by KevinZonda** [comment]
> 我看了下 `raw.fastgit.org.conf` 文件，是这句代码导致的。
> 
> 这句代码的意思是，反向代理时**告诉源服务器不要压缩**，而一般情况下无需添加这句代码，因为只有当你想要修改网页内容时（比如使用 `sub_filter` 来替换内容），才必须加上这个（否则会因为压缩而乱码）。
> 
> https://github.com/FastGitORG/nginx-conf/blob/a436ac717ae88c6916084d0542348efd6b2397a9/raw.fastgit.org.conf#L55
> 
> 去掉这段代码后，应该就会得到压缩后的文件了（由 Github 服务器压缩），即和 `raw.githubusercontent.com` 完全一样。

那是不是应该raw 移除这个
在hub等引入gzip呢？

**Comment by XIU2** [comment]
对。

`raw.fastgit.org.conf` 中没有修改网页内容的行为，因此该代码不仅无用，反而还会有副作用，所以建议**移除这行代码**。

> 仅这个 Raw 的，我觉得最少能节省一半的流量。  
> 我在我项目找了个文件试了下，[FastGit Raw](https://raw.fastgit.org/XIU2/UserScript/master/other/Autopage/rules.json) 目前是 ` 166 KB `，[Github Raw](https://raw.githubusercontent.com/XIU2/UserScript/master/other/Autopage/rules.json) 默认压缩后是 ` 33 KB `，即降低了 `80%`。

`hub.fastgit.org.conf` 中需要替换域名，因此这行代码是必须的，但可以开启 Gzip 来**提高网页访问速度 及 降低服务器流量宽带**。

**Comment by KevinZonda** [comment]
@XIU2 Hi, how it looks like now

**Comment by XIU2** [comment]
我看了下，[FastGit Raw](https://raw.fastgit.org/XIU2/UserScript/master/other/Autopage/rules.json) 目前依然有 ` 172 KB `，[Github Raw](https://raw.githubusercontent.com/XIU2/UserScript/master/other/Autopage/rules.json) 默认压缩后是 ` 34.8 KB `。
我没有在 FastGit Raw 的 Respinse Headers 中看到 `content-encoding: gzip` 标识。

**Comment by KevinZonda** [comment]
> 我看了下，[FastGit Raw](https://raw.fastgit.org/XIU2/UserScript/master/other/Autopage/rules.json) 目前依然有 ` 172 KB `，[Github Raw](https://raw.githubusercontent.com/XIU2/UserScript/master/other/Autopage/rules.json) 默认压缩后是 ` 34.8 KB `。
> 我没有在 FastGit Raw 的 Respinse Headers 中看到 `content-encoding: gzip` 标识。

并没有实现部署
先瞅瞅我最近的两条 commit

**Comment by XIU2** [comment]
我看了一遍没啥问题。

`gzip_comp_level 2` 比较合适，再高的话，压缩比提升并不大，但压缩时间和 CPU 占用会大幅增加。
`gzip_buffers 4 16k;` 需要根据使用时**内存占用情况**来判断是否需要调整。

另外 `hub.fastgit.org.conf` 因为只负责反代 `github.com` 主域名，而这个主域名下大都是 `document` 类型，以及一些 `fetch` 请求，没见到有其他静态资源（CSS、JS 什么的），因此 `gzip_types` 也不需要写那么多，当然这个多写也没影响~

毕竟静态资源都集中在 `assets.fastgit.org.conf` 域名中了，而这个域名并没有配置 `proxy_set_header Accept-Encoding "";` ，所以正常接受并反代了 Github 压缩后的文件。

**Comment by XIU2** [comment]
刚刚发现我这边访问 `raw.fastgit.org` 提示 `403 Forbidden` 。。。是在维护么？

**Comment by XIU2** [comment]
刚刚发现 `raw.fastgit.org` 恢复了，不过看了下发现还没有部署最新改动。。。
其实如果担心影响的话，可以先去改动 raw 的，hub 的毕竟都只是 document、fetch 请求，文件都不大，而且还需要在自己的服务器上面实时压缩，相比而言 raw 的就只是把反代时要求 Github 不压缩的那一行代码去掉了而已。

**Comment by KevinZonda** [comment]
403是因为DNS崩了
然后部署还要等待

**Comment by XIU2** [comment]
刚刚发现 `raw.fastgit.org` 不知道什么时候已经部署最新改动了，既然已经完成，那我就关闭啦~
