### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by gl0zzy** [FastGitORG/nginx-conf#33]
我在尝试用本项目部署一个Github镜像站, 但是遇到了一些问题.
项目中没有 codeload.fastgit.org.conf 和 customer-stories-feed.fastgit.org.conf
并且镜像站没有办法登录Github账号, 请求 https://域名/sessions/verified-device/mobile_poll 会返回 502

**Comment by gl0zzy** [comment]
在pr里找到了 codeload.fastgit.org.conf

**Comment by gl0zzy** [comment]
~nginx配置中加了 underscores_in_headers on;~
~现在登录会跳转到 https://域名/session 报 502 错误~
参考pr里的配置, 登录功能现在正常了

**Comment by KevinZonda** [comment]
codeload try #24

**Comment by KevinZonda** [comment]
so has the issue been completed?

**Comment by gl0zzy** [comment]
> so has the issue been completed?

customer-stories-feed.fastgit.org.conf 没有设置，不过不影响镜像站使用
